apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: employees
spec:
  containers:
  - name: webapp
    image: nginx:latest  # Will replace this with your GitHub Actions image later
    ports:
    - containerPort: 80
